### ISSUE TITLE
Follow DRY

### ISSUE THREAD

**Issue by prostomarkeloff** [kesha1225/Kumquat#2]
Your code doesn't follow DRY (**do not repeat yourself**).

https://github.com/kesha1225/Kumquat/blob/master/kumquat/application.py#L62
https://github.com/kesha1225/Kumquat/blob/master/kumquat/application.py#L80

... and others.

I think we should consider move that `assert` to `Route.__init__`.

**Comment by kesha1225** [comment]
I know, it's not ready yet

**Comment by kesha1225** [comment]
Thanks!
